language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install pytest pytest-runner pytest-cov pytest-mock python-mpd2 psutil requests codecov lxml
script:
  - pytest --cov=autosuspend
after_success:
  - codecov
